version: '3'

services:
  shared_rabbitmq:
    container_name: devaway-php_skeleton-rabbitmq
    image: 'rabbitmq:3.7-management'
    restart: unless-stopped
    ports:
      - 5630:5672
      - 8090:15672
    environment:
      - RABBITMQ_DEFAULT_USER=devaway
      - RABBITMQ_DEFAULT_PASS=d3v4w4y

  shared_prometheus:
    container_name: devaway-php_skeleton-prometheus
    image: prom/prometheus:v2.1.0
    volumes:
      - ./etc/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9999:9090

  database_mysql:
    container_name: devaway-php_skeleton-database-mysql
    image: mysql:8.0
    ports:
      - 3360:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "mysqladmin", "--user=root", "--password=", "--host=127.0.0.1", "ping", "--silent"]
      interval: 2s
      timeout: 10s
      retries: 10
    command: ["--default-authentication-plugin=mysql_native_password"]

  backoffice_backend_php:
    container_name: devaway-php_skeleton-backoffice_backend-php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8040:8040"
      - "9040:9001"
    volumes:
      - .:/app:delegated
    depends_on:
      - shared_rabbitmq
      - shared_prometheus
    command: symfony serve --dir=apps/backoffice/backend/public --port=8040 --force-php-discovery

  backoffice_frontend_php:
    container_name: devaway-php_skeleton-backoffice_frontend-php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8041:8041"
      - "9041:9001"
    volumes:
      - .:/app:delegated
    depends_on:
      - shared_rabbitmq
      - shared_prometheus
      - database_mysql
    command: symfony serve --dir=apps/backoffice/frontend/public --port=8041 --force-php-discovery
